language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-23
script:
- "./gradlew build"
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
deploy:
  provider: releases
  api_key:
    secure: hGKL6LShXq9HtZ+k6E0kYEVi7j6wp7ptBRqK9aoTlpxc2fkJCtWLP/hs/xZidC+03QvC2L+sytirdYfxLjr0ZequiHET/sS7Sgqwl1wL6sThYHrAb64B3NgTfWMrMHFAmJ2c8H6oZNCkJUtkUjgxI15m5Y6jt8oFke6Zrfkt+Dkm1sJJ8AsyR4v4k8otgj8bs9sXhOFsNc+L69kDhFN9XsMXji1BtQbFrLp+40d59k7Jr9SV+hVRsLZio4z9zKf4Q0fx5cmBrGXPwag34cVScJR84UG5KglkWVN89V8ZuS+aSVHc+UMJHYJisfZsfrE5iQn2YFiiznKKB9/PYOGHdv9YKoGuw81gTejbi6og+9L9pY2zrR5ElzU39LyEPUhurTadBsFi4jhILhYR9zAv6lwTwi5aPkwgCcvuLjpTk6EYmtRmd+w+FFcGrgpWVZ+OXZQxsYPw+xTvgwR1PvHSz2/kAoH8QaEcwWASC9UVfD9uSbsvNp1wq2uuDUlj4Bxm8sRnrfdE7gBSCT9IPS9eXmaQJDPDtC+UlQ3E3lRj7KA+ot2cdxI2pMynz52w2EiIArwsRSbS6dXJeV+dZ+aTpGE/YOvy675y6yz8CuDEU0LYOrKqpGDh1HehXDUIAC1fi7qjgKzA/RGfpOpV/aTO9hBRfq5k4Qh0DnikUr0Enj0=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: mdicke2s/BicycleKaraoke
    tags: true
before_script:
- echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    #- sys-img-x86-android-17

script:
  - ./gradlew build

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
# deploy to github releases as described here https://github.com/pockethub/PocketHub/issues/770
deploy:
  provider: releases
  api_key:
    secure: hGKL6LShXq9HtZ+k6E0kYEVi7j6wp7ptBRqK9aoTlpxc2fkJCtWLP/hs/xZidC+03QvC2L+sytirdYfxLjr0ZequiHET/sS7Sgqwl1wL6sThYHrAb64B3NgTfWMrMHFAmJ2c8H6oZNCkJUtkUjgxI15m5Y6jt8oFke6Zrfkt+Dkm1sJJ8AsyR4v4k8otgj8bs9sXhOFsNc+L69kDhFN9XsMXji1BtQbFrLp+40d59k7Jr9SV+hVRsLZio4z9zKf4Q0fx5cmBrGXPwag34cVScJR84UG5KglkWVN89V8ZuS+aSVHc+UMJHYJisfZsfrE5iQn2YFiiznKKB9/PYOGHdv9YKoGuw81gTejbi6og+9L9pY2zrR5ElzU39LyEPUhurTadBsFi4jhILhYR9zAv6lwTwi5aPkwgCcvuLjpTk6EYmtRmd+w+FFcGrgpWVZ+OXZQxsYPw+xTvgwR1PvHSz2/kAoH8QaEcwWASC9UVfD9uSbsvNp1wq2uuDUlj4Bxm8sRnrfdE7gBSCT9IPS9eXmaQJDPDtC+UlQ3E3lRj7KA+ot2cdxI2pMynz52w2EiIArwsRSbS6dXJeV+dZ+aTpGE/YOvy675y6yz8CuDEU0LYOrKqpGDh1HehXDUIAC1fi7qjgKzA/RGfpOpV/aTO9hBRfq5k4Qh0DnikUr0Enj0=
  file: app/build/outputs/apk/app-release.apk
  # do not delete the files we're trying to upload
  skip_cleanup: true
  on: # we are on this repo
    repo: mdicke2s/BicycleKaraoke
    # and we are building a tag
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_03c737da6729_key -iv $encrypted_03c737da6729_iv
  -in android.jks.enc -out android.jks -d
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
